apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: auto-scale-runners
spec:
  replicas: 1
  maxRunnerLimit: 5
  template:
    spec:
      configURL: https://github.com/bbq-beets/ting-test
      githubTokenSecretKeyRef:
        name: githubtoken
        key: GITHUB_PAT

