apiVersion: v1
items:
- apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2020-08-05T19:14:04Z"
    name: runner-deployment
    namespace: default
    resourceVersion: "167447"
    selfLink: /apis/autoscaling/v2beta2/namespaces/default/horizontalpodautoscalers/runner-deployment
    uid: 54d86943-eca9-468c-9698-c843f6b6183a
  spec:
    maxReplicas: 10
    metrics:
    - type: Object
      object:
        metric:
          name: test-metric
        describedObject:
          apiVersion: v1
          kind: Service
          name: kubernetes
        target:
          type: Value
          value: 300m
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: runner-deployment
  status:
    conditions:
    - lastTransitionTime: "2020-08-05T19:14:19Z"
      message: the HPA controller was able to get the target's current scale
      reason: SucceededGetScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2020-08-05T19:14:19Z"
      message: 'the HPA was unable to compute the replica count: unable to get metrics
        for resource cpu: no metrics returned from resource metrics API'
      reason: FailedGetResourceMetric
      status: "False"
      type: ScalingActive
    currentMetrics: null
    currentReplicas: 1
    desiredReplicas: 0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
