---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-patcher
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-patcher
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-patcher
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: githubtoken
type: Opaque
stringData:
  GITHUB_PAT: "xxx"